- name: "run container with ansible"
  hosts: localhost
  connection: local

  tasks:
    - name: stop current container
      command: docker stop lo-fi-container
      ignore_errors: yes

    - name: delete current container
      command: docker rm lo-fi-container
      ignore_errors: yes

    - name: delete existing web container
      command: docker rm web-container
      ignore_errors: yes

    - name: delete current img
      command: docker rmi lo-fi-img
      ignore_errors: yes

    - name: build docker image to Lo-Fi
      command: docker build -t lo-fi-img .

    - name: create tag to image
      command: docker run -d --name web-container -p 5000:80 lo-fi-img
