---
- name: "run container with ansible"
  host: localhost
  connection: local

  tasks:
  - name: stop current container
   command: docker stop Lo-Fi-container
   ignore-errors: yes


  - name: delete current container
   command: docker rm Lo-Fi-container
   ignore-errors: yes

  - name: delete current img
   command: docker rmi Lo-Fi-image
   ignore-errors: yes

  - name: build docker image to Lo-Fi
   command: docker build -t Lo-Fi-container .

  - name: create tag to image
   command: docker run -d  --name web-container -p 5000:80 Lo-Fi-image