---
- name: "run container with ansible"
  host: localhost
  connection: local
  tasks:
    - name: stop current container
      command: docker stop lo-fi-container

    - name: remove current container
      command: docker rm lo-fi-container

    - name: run new container
      command: docker run -d --name lo-fi-container -p 5000:80 lo-fi-img

