---
- hosts: localhost
  tasks:
    - name: check if lo-fi-container is running
      command: docker ps -q --filter "name=lo-fi-container"
      register: container_check
      ignore_errors: true

    - name: stop current container
      command: docker stop lo-fi-container
      when: container_check.stdout != ""

    - name: remove current container
      command: docker rm lo-fi-container
      when: container_check.stdout != ""

    - name: run new container
      command: docker run -d --name lo-fi-container -p 5000:80 lo-fi-img
